services:
  - type: web
    name: nexacare-api
    runtime: docker
    plan: free
    region: singapore
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FCM_SERVICE_ACCOUNT_JSON
        sync: false
